### ISSUE TITLE
Test-issue

### ISSUE THREAD

**Issue by cwsjitu** [ryan-ncbs/SECR-Simulation-Analysis#1]
please create a file suppose secrCode.R. We might be able to access them.

Jitu

**Comment by cwsjitu** [comment]
`##set your working directory with 
# setwd()

library(secr)
library(raster)
library(rgdal)
library(sp)
library(maptools)
library(rgeos)
library(dplyr)

## coordinate system
latlong = "+init=epsg:4326" ## LatLon Projection
ingrid = "+init=epsg:32643" ## UTM Projection

## assumptions to generate capture history
 N <-          ## Number of individuals/activity centers      
 traploc <-    ## Number of trap locations
 g0 <-         ## value between 0.1 and 0.3
 sigma <-      ## depends on home range of species
 occasions <- 10  ## 10 sampling occasions  `

**Comment by rgryan** [comment]
Hey Jitu, I've put up a code that generates the individuals and camera trap locations on the raster. Let me know if you can access it or not.

**Comment by cwsjitu** [comment]
Great. I can see it.
